# Generated by Django 2.2.4 on 2019-09-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=150),
        ),
    ]
