# Generated by Django 2.2.4 on 2019-11-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=150)),
                ('github_url', models.CharField(max_length=100)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120)),
                ('first_definition', models.TextField(max_length=250)),
                ('first_ex', models.CharField(blank=True, max_length=120)),
                ('second_definition', models.TextField(blank=True, max_length=250)),
                ('second_ex', models.CharField(blank=True, max_length=120)),
                ('third_definition', models.TextField(blank=True, max_length=250)),
                ('third_ex', models.CharField(blank=True, max_length=120)),
                ('synonym', models.CharField(blank=True, max_length=120)),
                ('more_definitions', models.TextField(blank=True)),
                ('creator', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
