# Generated by Django 2.2.4 on 2019-09-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('first_definition', models.CharField(max_length=120)),
                ('first_ex', models.CharField(blank=True, max_length=120)),
                ('second_definition', models.CharField(blank=True, max_length=120)),
                ('second_ex', models.CharField(blank=True, max_length=120)),
                ('third_definition', models.CharField(blank=True, max_length=120)),
                ('third_ex', models.CharField(blank=True, max_length=120)),
                ('synonym', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
