# Generated by Django 2.2.4 on 2019-11-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
