# Generated by Django 2.2.4 on 2019-11-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191110_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='user',
            new_name='creator',
        ),
    ]
