# Generated by Django 2.2.4 on 2019-09-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='more_definitions',
            field=models.TextField(blank=True),
        ),
    ]
