# Generated by Django 2.2.4 on 2019-11-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191110_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='creator',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
