# Generated by Django 2.2.4 on 2020-02-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_word_dict_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='dict_ref',
        ),
    ]
