# Generated by Django 2.2.4 on 2019-09-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190924_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='first_definition',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='word',
            name='second_definition',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='word',
            name='third_definition',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
