# Generated by Django 2.2.4 on 2020-03-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_word_dict_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='first_ex',
            new_name='example',
        ),
        migrations.RemoveField(
            model_name='word',
            name='first_definition',
        ),
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.TextField(default='null', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='word',
            name='second_definition',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='word',
            name='third_definition',
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=20),
        ),
    ]
