# Generated by Django 2.2.4 on 2020-03-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200317_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='more_definitions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='second_definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
